### ISSUE TITLE
Auto Draw 2.1 Suspended in Task Manager

### ISSUE THREAD

**Issue by priyanshurajraj** [auto-draw/autodraw#3]
When i tried to run exe . The auto Draw 2.1 showed suspended in Task Manager . and the exe file do not open. How can i fix this ?? 
![Screenshot (5724)](https://github.com/auto-draw/autodraw/assets/26685478/6f3ede38-d8ee-4be8-ad3e-86618846cb27)

**Comment by AlexDalas** [comment]
That's not good. Can you share what your config looks like in 'C:\Users\USERNAME\AppData\Local\AutoDraw\config.json'?

**Comment by priyanshurajraj** [comment]
> That's not good. Can you share what your config looks like in 'C:\Users\USERNAME\AppData\Local\AutoDraw\config.json'?

Sir i do not understand what are you saying . Please Help me

**Comment by priyanshurajraj** [comment]
> That's not good. Can you share what your config looks like in 'C:\Users\USERNAME\AppData\Local\AutoDraw\config.json'?

1. sir there is a log file which contains error i think. Sir pls provide me solution after reading it. one file is of yesterday and one is today

[06.05.2024.txt](https://github.com/auto-draw/autodraw/files/15227210/06.05.2024.txt)
[07.05.2024.txt](https://github.com/auto-draw/autodraw/files/15227213/07.05.2024.txt)

2. there is config.json file also but it is empty.

**Comment by priyanshurajraj** [comment]
> > That's not good. Can you share what your config looks like in 'C:\Users\USERNAME\AppData\Local\AutoDraw\config.json'?
> 
> 1. sir there is a log file which contains error i think. Sir pls provide me solution after reading it. one file is of yesterday and one is today
> 
> [06.05.2024.txt](https://github.com/auto-draw/autodraw/files/15227210/06.05.2024.txt) [07.05.2024.txt](https://github.com/auto-draw/autodraw/files/15227213/07.05.2024.txt)
> 
> 2. there is config.json file also but it is empty.

![Screenshot (5733)](https://github.com/auto-draw/autodraw/assets/26685478/f34bd175-daf0-4f0c-a392-6c9dc454e86e)

**Comment by Siydge** [comment]
Closing this as its turned stale, please contact for future support in the [Discord](https://discord.gg/2rvVtb32qA) rather than over GitHub
